events {
    worker_connections 1024;
}

http {

    upstream clinica_app {
        server app:3000;
    }

    server {
        listen 80;
        server_name _;

        # Logs
        access_log /var/log/nginx/access.log;
        error_log  /var/log/nginx/error.log;

        # Proxy a la app
        location / {
            proxy_pass         http://clinica_app;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection 'upgrade';
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_cache_bypass $http_upgrade;
        }

        # Health check directo
        location /health {
            proxy_pass http://clinica_app/health;
        }

        # Métricas solo accesible internamente
        location /metrics {
            proxy_pass http://clinica_app/metrics;
            allow 127.0.0.1;
            deny  all;
        }
    }
}
